### ISSUE TITLE
Not getting into game.

### ISSUE THREAD

**Issue by obelisk79** [begin-theadventure/lutris-scripts#1]
Followed your guide, installed R5 and Flowstate propertly.

I get the EA launcher, log in, then restart the banner in lutris and get the following: 
![image](https://user-images.githubusercontent.com/17993710/220216347-b7f0bb9c-afc6-4cdb-8eb3-3c81cd1e1bdf.png)

Then the game closes out.

**Comment by begin-theadventure** [comment]
On [Discord](https://discord.com/channels/873158454850756638/1018476411956232232/1023319487841312839) they wrote that the solution is to run the game with -dev -novid.
Try it in Lutris: right click on the banner -> Configuration -> Game Options -> Arguments: -dev -novid

**Comment by obelisk79** [comment]
This worked, thanks.
